badge-server-url: http://badges.falsifiable.us
metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  convolutional-siamese:
    envs:
      local/earthquake:
        args: !!set
          --ipc=host: null
          --runtime=nvidia: null
          --volume=/home/prem/research/earthquakes/:/exp: null
    parameters:
    - split: SAC_20010126_XF_prem
    - split: SAC_20021102_XF_prem
    - split: SAC_20030925_XF_prem
    - split: SAC_20030927_XF_prem
    - split: SAC_20041226_2_XF_prem
    - split: SAC_20041226_XF_prem
    - split: SAC_20050328_XF_prem
    - split: SAC_20050724_XF_prem
    - split: SAC_20100227_Chile_prem
    path: pipelines/convolutional-siamese
    requirements: {}
    stages:
    - train
    - test
    timeout: 0
  create-docker-environment:
    envs:
      host:
        args: []
    path: pipelines/create-docker-environment
    stages:
    - build-docker-image
    - launch-services
  create-virtual-environment:
    envs:
      host:
        args: []
    parameters: []
    path: pipelines/create-virtual-environment
    requirements: {}
    stages:
    - setup
  fully-connected-siamese:
    envs:
      local/earthquake:
        args: !!set
          --ipc=host: null
          --runtime=nvidia: null
          --volume=/home/prem/research/earthquakes/:/exp: null
    parameters: []
    path: pipelines/fully-connected-siamese
    requirements: {}
    stages:
    - train
    - test
    timeout: 0
  prepare-data:
    envs:
      local/earthquake:
        args: !!set
          --ipc=host: null
          --runtime=runc: null
          --volume=/home/prem/research/earthquakes/data:/data: null
    path: pipelines/prepare-data
    requirements: {}
    stages:
    - create-dataset
    vars: []
popperized:
- github/popperized
version: 1
